### PR TITLE
Fix: Missing object property lookup restoreUserAnswers, getFeedback, ItemsQuestionModel (fixes #507)

### LINKED ISSUE #507: Defensive code for poor state restoration
### Subject of the issue
There are some instances where the code assumes object properties have values but where the code should return early when the values are missing and the code does currently not return early.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #507 

### Fix
* missing _userAnswer in restoreUserAnswers
* getFeedback missing activeItem

### CODE REVIEW

**Review by swashbuck — APPROVED** [review]
👍

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍

**Pull request merged**
