### PR TITLE
Fix: Added default text for displayTitle of content schema

### PR DESCRIPTION
**Pull request by zubairslamdien**
Fixes adapt-security/adapt-authoring-ui/issues/206

The initial value of title and displayTitle must be the same in order for the locking behaviour in the AAT UI to apply.
### Reference
* [adapt-authoring-ui:scaffoldDisplayTitleView.js](https://github.com/adapt-security/adapt-authoring-ui/blob/c28f1385c960990ad0e15fa1fcd86a6896fc498b/app/modules/scaffold/views/scaffoldDisplayTitleView.js#L49)

### Fix
* Default text added to displayTitle in content.schema.json

### CODE REVIEW

**Comment by oliverfoster** [comment]
Why is this necessary?

**Comment by zubairslamdien** [comment]
Needed for adapt-security/adapt-authoring-ui/issues/206

**Comment by oliverfoster** [comment]
What I mean is: How does supplying a default fix the relationship behaviour?

**Comment by oliverfoster** [comment]
I have update the pr comment with a reference to (I think) the code in question and added an explanation as to why this pr fixes the issue.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Pull request merged**
