### PR TITLE
Allow score to be set if _requireAssessmentCompleted is false

### PR DESCRIPTION
**Pull request by deltanetdan**
Move the check for _requireAssessmentCompleted to onAssessmentComplete. Fix for #55

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by ethan-lp — APPROVED** [review]

**Review by eleanor-heath — APPROVED** [review]

**Comment by deltanetdan** [comment]
Actually I think _shouldSubmitScore needs adding to config.model.schema as well

**Comment by oliverfoster** [comment]
I'm just waiting for a spec for the new schema from @taylortom before we go editing them. I guess it just follows json schema for the most part and should be a copy/paste from any other boolean property.

**Comment by oliverfoster** [comment]
schema can be sorted in another pr

**Pull request merged**
