### PR TITLE
New: Added isArrowable and fixed input[type=radio] in popup bug

### LINKED ISSUE #378: Arrow keys are prevented by scroll handler in popup when on input[type=radio]
### Subject of the issue
Arrow keys are prevented by the popup scroll handler, when in popup on an `input[type=radio]`, where arrow keys should toggle the selection.

Adapt assumes arrow keys used in a popup are for scrolling. In some extensions arrow keys are used to move the checked item on an `input[type=radio]` element. Adapt should behave accordingly.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #378 

### Fix
* `input[type=radio]` in popup bug

### New
* Added `a11y.isArrowable`

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-replin — APPROVED** [review]
This works well for me.

**Review by joe-allen-89 — APPROVED** [review]
👍

**Pull request merged**
