### PR TITLE
Fix: Device resize html classes rendering speed (fixes #209)

### LINKED ISSUE #209: Improve responsiveness of html classes for device size changes
### Subject of the issue
https://github.com/adaptlearning/adapt-contrib-core/blob/5444496e919d760f416b654b7f4d728b7bd29807/js/device.js#L18

`onWindowResize` is debounced by 100ms meaning that there is a callback queue + event loop lag plus 100ms before the classes change. These should change on a requestAnimationFrame as soon as practically possible.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #209 

### Fix
* Changed device resize html classes changes to occur on animation frames as soon as possible

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by StuartNicholls — APPROVED** [review]

**Review by joe-allen-89 — APPROVED** [review]
Tested locally using FW v5.20.0 with chrome using device toolbar and spamming rotate, all working as expected.

**Review by kirsty-hames — APPROVED** [review]
Much smoother thank you - fires on the pixel change

**Review by guywillis — APPROVED** [review]
👍  Tested on:

MacBook Pro Monterey v12.4 - Chrome
iPhone SE v15.4 - Safari
Samsung Galaxy Tab A7 v11 - Chrome

**Pull request merged**
