### PR TITLE
Fix: Recalculate nav height on button addition

### LINKED ISSUE #564: Navigation bar height calculation error
### Subject of the issue
If the menu has no buttons then the height is not recalculated moving into a page, when the back button appears.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #564 

### Fix
* Recalculate nav height on button addition

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by guywillis — APPROVED** [review]
👍

**Review by kirsty-hames — APPROVED** [review]
Works as expected thanks 👍 Testing in Chrome, FF and Safari on Mac.

**Pull request merged**
