### PR TITLE
Fix: Added _isRendered: true to main view render

### LINKED ISSUE #393: Fix: Main view is never marked as _isRendered
### Subject of the issue
This pr https://github.com/adaptlearning/adapt-contrib-core/pull/388:
https://github.com/adaptlearning/adapt-contrib-core/blob/a6304f4cbb16d5c827a4ebbc9afb253f0898ead1/js/views/adaptView.js#L87-L106
Adds a check when rendering, to see if the model has been marked as `_isRendered` from the `addChildren` function.
https://github.com/adaptlearning/adapt-contrib-core/blob/6ef84972f04cb760fb2862b0ba44990aeca73a24/js/views/adaptView.js#L149-L197
Which means that main menus made from jsx won't render correctly, as the router never sets the main view is `_isRendered: true`.

The lifecycle of the `_isRendered` property should be set to `true` when the view is being rendered by the router or by the view's `addChildren` property and then removed when `Adapt.remove()` has been called.
https://github.com/adaptlearning/adapt-contrib-core/blob/6ef84972f04cb760fb2862b0ba44990aeca73a24/js/adapt.js#L196-L212

### PR DESCRIPTION
**Pull request by oliverfoster**
fix #393 

### Fix
* Added _isRendered: true to the main view render

### CODE REVIEW

**Review by guywillis — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Pull request merged**
