### PR TITLE
issue/87 Moved deprecated warnings

### LINKED ISSUE #87: Tidy singleton deprecated warnings into one file

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #87 

I think It makes more sense to have these in one place rather than polluting all of their modules.

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by eleanor-heath — APPROVED** [review]

**Review by joe-allen-89 — CHANGES_REQUESTED** [review]
@oliverfoster Tested with v5.19.3, as we've removed accessibility.js we'll need to remove 'import 'core/js/accessibility';' from app.js as it's currently throwing an error whilst compiling.

**Comment by oliverfoster** [comment]
Done, thanks. Good catch.

**Review by joe-allen-89 — APPROVED** [review]
Tested with FW v5.19.3, loading and working as expected.

**Pull request merged**
