### PR TITLE
New: Added config.json:_disablePageHeaders (fixes #559)

### LINKED ISSUE #558: Allow disablement of page headers
### Subject of the issue
This is to allow trying alternative page header styles in a simple way.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #558 

### New
* Added config.json:_disablePageHeaders

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by guywillis — APPROVED** [review]
👀

**Review by kirsty-hames — APPROVED** [review]
Works as expected thanks 👍

**Pull request merged**
