### PR TITLE
Fix: Set _isAssessmentPassed correctly (fixes #474)

### LINKED ISSUE #474: Set _isAssessmentPassed properly
### Subject of the issue
Whilst fixing the issues of the assessment score needing to be sent to the lms before its completion status, for the LMS CornerStone, the setting of _isAssessmentPassed was removed.

See issue https://github.com/adaptlearning/adapt_framework/issues/2604 and pull requests https://github.com/adaptlearning/adapt_framework/issues/2604 https://github.com/adaptlearning/adapt-contrib-core/pull/30/files

It's helpful to have this property set as we use it for console output in spoor via https://github.com/adaptlearning/adapt-contrib-spoor/blob/4370780b00d734819159acb866ace308d5ec59f0/js/adapt-stateful-session.js#L124-L127 and https://github.com/adaptlearning/adapt-contrib-spoor/blob/4370780b00d734819159acb866ace308d5ec59f0/js/adapt-stateful-session.js#L165

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #474 

### Fix
* Correctly set _isAssessmentPassed as it had been mistakenly removed

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by Ant6009** [comment]
👀

**Review by joe-allen-89 — APPROVED** [review]
👍

**Pull request merged**
