### PR TITLE
Update: inview.js to use IntersectionObserver

### LINKED ISSUE #578: inview update to use IntersectionObserver instead of manual calculations
### Subject of the issue
[IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) is now long fully supported https://caniuse.com/intersectionobserver

It works in a similar way to MutationObserver, in that it allows well timed callbacks against the browser's rendering lifecycle, giving us the ability to immediately capture onscreen events as they happen and respond to them in a way that doesn't cause rendering glitches. It is much more performant and much less resource intensive than our current approach of measuring and comparing on expiring intervals and at strategic events.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #578

### Update
* Use browser API [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver) to reduce code complexity and increase performance

Refs:
* https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver
* https://caniuse.com/intersectionobserver

Note:
* Not ie11 compatible

### CODE REVIEW

**Comment by oliverfoster** [comment]
Ready now, apologies

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by joe-allen-89 — APPROVED** [review]
Tested with bookmarking on chrome, firefox and edge, all working as expected 👍

**Review by StuartNicholls — APPROVED** [review]

**Pull request merged**
