### PR TITLE
Fix: Fallback value of title used for component feedback when _feedback.title not set (509)

### LINKED ISSUE #509: Component feedback title not falling back to component title
### Subject of the issue/enhancement/features
Describe your issue here.

### Your environment
* FW v5.36.2 (Core v6.45.6)

### Steps to reproduce
Use MCQ on a course and leave the Feedback title blank.

### Expected behaviour
The help text indicates that component title will be used as if this field is left empty

### Actual behaviour
No title displayed on component feedback

### PR DESCRIPTION
**Pull request by cahirodoherty-learningpool**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
Fixes #509 

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Fallback value of title used for component feedback when _feedback.title not set

### CODE REVIEW

**Comment by oliverfoster** [comment]
Could we resolve these issues please?
@kirsty-hames @joe-allen-89 @cahirodoherty-learningpool 

These fallback keep coming and going:
* Added originally by Cahir https://github.com/adaptlearning/adapt-contrib-core/pull/416
* Removed by Kirsty and Joe https://github.com/adaptlearning/adapt-contrib-core/pull/428

**Comment by cahirodoherty-learningpool** [comment]
> It seems it must be possible to leave the feedback `title` empty in order for `altTitle` to work. Invariably most components will have either a `displayTitle` or a `title` so if either property is used as a default for feedback title, then `altTitle` never gets applied.
Yes, I'm a little confused as to the actual code around `altTitle` and `altFeedbackTitle`. `altFeedbackTitle` is the schema property, but I don't think the code actually ever reads that; Instead we have https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/models/questionModel.js#L287, but `altTitle` won't exist to be read at that point. I think its just a typo, and not central to your argument here Oliver, but worth noting.

> Why should the feedback title default to the question `displayTitle` or `title`?
This is driven by user expectations from how it was working before and the helper text found on many components, e.g. https://github.com/adaptlearning/adapt-contrib-mcq/blob/master/properties.schema#L243

**Comment by kirsty-hames** [comment]
> Yes, I'm a little confused as to the actual code around `altTitle` and `altFeedbackTitle`. `altFeedbackTitle` is the schema property, but I don't think the code actually ever reads that; Instead we have https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/models/questionModel.js#L287, but `altTitle` won't exist to be read at that point. I think its just a typo, and not central to your argument here Oliver, but worth noting.

`altFeedbackTitle` is a global title, set once in _course.json_ rather than per component feedback. `altTitle` is set per question feedback and overrides `altFeedbackTitle`. Neither title display on screen and are used by screen readers.

Notify requires a title as this is used to [label](https://github.com/adaptlearning/adapt-contrib-core/blob/6657b362f59cccbb71e49b0e306227fd7c25ddce/js/views/notifyPopupView.js#L17) the Notify 'dialog' popup (see [ticket for ref](https://github.com/adaptlearning/adapt-contrib-core/issues/483)).

If we're providing a fallback title (`title` and/or `displayTitle`), then `altFeedbackTitle` and `altTitle` should be removed as these won't get applied. Before removing, is there a use case for keeping alt titles? e.g. if using inline feedback displaying a title for the question and feedback can become repetitive etc. I couldn't find the issue/PR for why `altTitle` got added in the first place but I have seen these used in projects in favor of displaying a title. Do people have a preference?

**Comment by oliverfoster** [comment]
@kirsty-hames 

`altTitle` original [pr](https://github.com/adaptlearning/adapt-contrib-core/pull/201) and [issue](https://github.com/adaptlearning/adapt-contrib-core/issues/173)

Including @chris-steele

**Comment by cahirodoherty-learningpool** [comment]
> > Yes, I'm a little confused as to the actual code around `altTitle` and `altFeedbackTitle`. `altFeedbackTitle` is the schema property, but I don't think the code actually ever reads that; Instead we have https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/models/questionModel.js#L287, but `altTitle` won't exist to be read at that point. I think its just a typo, and not central to your argument here Oliver, but worth noting.
> 
> `altFeedbackTitle` is a global title, set once in _course.json_ rather than per component feedback. `altTitle` is set per question feedback and overrides `altFeedbackTitle`. Neither title display on screen and are used by screen readers.
> 
> Notify requires a title as this is used to [label](https://github.com/adaptlearning/adapt-contrib-core/blob/6657b362f59cccbb71e49b0e306227fd7c25ddce/js/views/notifyPopupView.js#L17) the Notify 'dialog' popup (see [ticket for ref](https://github.com/adaptlearning/adapt-contrib-core/issues/483)).
> 
> If we're providing a fallback title (`title` and/or `displayTitle`), then `altFeedbackTitle` and `altTitle` should be removed as these won't get applied. Before removing, is there a use case for keeping alt titles? e.g. if using inline feedback displaying a title for the question and feedback can become repetitive etc. I couldn't find the issue/PR for why `altTitle` got added in the first place but I have seen these used in projects in favor of displaying a title. Do people have a preference?

Taking a look at the hbs file, it seems we are reading the models `altTitle` in the elseif. I think this should actually be `altFeedbackTitle` as that is the custom property pushed onto the model based on feedback.altTitle || _globals.altFeedbackTitle if we are going to keep altTitle. Also, the difference in the title and altTitle html is minimal. Perhaps we can move all the setting of display logic into the View to help clarify our fallbacks.

I'll add this to the current PR for a bit of a cleanup, but we should definitely resolve what our fallbacks are and in which order

**Comment by cahirodoherty-learningpool** [comment]
I've updated the PR to simplify the hbs by pushing display logic more on the view. We still have the decision to make over the fields we sequentially fall back on for the feedbackTitle field that gets resolved here though, but hopefully it's now easier to see that order

**Comment by kirsty-hames** [comment]
> I've updated the PR to simplify the hbs by pushing display logic more on the view. We still have the decision to make over the fields we sequentially fall back on for the feedbackTitle field that gets resolved here though, but hopefully it's now easier to see that order

Thanks @cahirodoherty-learningpool, this is much clearer. When I update to your latest [commit]([4bd9b57](https://github.com/adaptlearning/adapt-contrib-core/pull/510/commits/4bd9b57be3f29c7665ea59910e80c0fb585200f4)) however no title is rendering for me regardless which title I set (title, altTitle or altFeedbackTitle).

In terms of order, I'd propose the following:
`_feedback.title` with default of 'Feedback'. If left empty, no visual title will display, only an `aria-label` title will render (altTitle or altFeedbackTitle).
`_feedback.altTitle` with no default. Optional if question specific alt text is required.
`_globals._accessibility.altFeedbackTitle` with default of 'Feedback'. Ensures the Feedback always has a label for accessibility.

Reviewing some recent courses, I find feedback title text is one of the following:
Feedback,
Content specific title,
Blank (with an aria-label 'Feedback').

If we want to use the component `title`/`displayTitle` as a fallback I'm not sure how we would add this other than providing a config option. If so, is using `title`/`displayTitle` as a fallback typically done globally for a course or per question instance?

**Review by joe-allen-89 — APPROVED** [review]
👍

**Pull request merged**
