### PR TITLE
Fix: Ensure marking appears only when canShowMarking is enabled

### PR DESCRIPTION
**Pull request by eleanor-heath**
Fixes [issue/356](https://github.com/adaptlearning/adapt-contrib-core/issues/356)

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by swashbuck — APPROVED** [review]
👍

**Comment by eleanor-heath** [comment]
> @eleanor-heath I actually couldn't reproduce this, but your changes seem sound.
> 
> > Enable "Set pass mark".
> > Set pass mark to 100.
> > Set question submission to "per question".
> 
> Could you let me know what exact settings these relate to? In my assessment article, I'm using:
> 
> ```
>     "_assessment": {
>       "_isEnabled": true,
>       "_id": "a-15",
>       "_suppressMarking": false,
>       "_scoreToPass": 100,
>       "_correctToPass": 100,
>       "_isPercentageBased": true,
>       "_includeInTotalScore": true,
>       "_assessmentWeight": 1,
>       "_isResetOnRevisit": true,
>       "_attempts": "infinite",
>       "_allowResetIfPassed": false,
>       "_scrollToOnReset": false,
>       "_banks": {
>         "_isEnabled": true,
>         "_split": "2,2",
>         "_randomisation": true
>       },
>       "_randomisation": {
>         "_isEnabled": false,
>         "_blockCount": 1
>       },
>       "_questions": {
>         "_resetType": "hard",
>         "_canShowFeedback": true,
>         _"_canShowMarking": true,_
>         "_canShowModelAnswer": true
>       }
>     },
> ```

Hi @swashbuck, it relates to _canShowMarking within _questions, I have italicised the property it relates to above.

**Comment by guywillis** [comment]
Hi @eleanor-heath, 

Like @swashbuck, I am also struggling to replicate the issue but I think the changes made make sense. 

> ### Steps to reproduce
> 1. Create a course with a Multiple Choice question component.
> 2. Add the Multiple Choice Question to an assessment.
> 3. Set the question submission to “per question”.
> 4. Enable "Set pass mark".
> 5. Set pass mark to 100.
> 6. Set question submission to "per question".
> 7. Disable show marking.

Would you mind detailing the corresponding json config for steps 3 to 7 and which file they should be edited in please

**Comment by eleanor-heath** [comment]
> * Set the question submission to “per question”.
> * Enable "Set pass mark".
> * Set pass mark to 100.
> * Set question submission to "per question".

Hi @guywillis,

I have only realised most of those steps are not applicable to you, the only settings within an assessment that looks to be applicable to you are the `"_canShowMarking": false,` and pass mark which comes from the `_scoreToPass` property.

**Comment by guywillis** [comment]
I was able to replicate the issue after answering the question, navigating to another page within the course, and then back again to the assessment. 

Applying the fix within this pull resolved the issue.

**Review by guywillis — APPROVED** [review]
👍

**Pull request merged**
