### PR TITLE
Fix: Inview locking and triggering (fixes #588)

### LINKED ISSUE #588: inview animations not triggered on page load
### Subject of the issue
When a page first loads, inview animations are not triggered until the user starts to scroll down the page.

Relates to:
https://github.com/adaptlearning/adapt-contrib-core/pull/579

### Your environment
* FW 5.41.3
* Core 6.56.0
* Mac Firefox / Chrome

### Steps to reproduce
Make the following changes to the Vanilla course that is created from `adapt create course`. These steps are not necessary but assist with reproducing the issue.

1. **co-100**: Add `hide-page-header` to `_htmlClasses`
2. **b-100** and **b-105**: Use `_onScreen` animations with `_percentInviewVertical` set to `1`
3. **Vanilla theme**: In _less/_defaults/_animations.less_, set `@animation-delay` to `0s`
4. View the **co-100** page

### Expected behaviour
Blocks should immediately animate in.

### Actual behaviour
Blocks do not animate until you start scrolling down the page.

### Screen recording
https://github.com/user-attachments/assets/889cfcd5-2631-4085-9499-e46ca84604af

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #588 

### Fix
* Moved item processing into one unified function making the rules clearer
* Fixed locking so that it processes correctly on unlocks
* Fixed locking so that adds and removes potential duplicate locks correctly

### CODE REVIEW

**Review by swashbuck — APPROVED** [review]
👍

**Comment by oliverfoster** [comment]
inview
@chris-steele inview seems to be complete fine from here, could you try with the last commits please?

**Comment by chris-steele** [comment]
@oliverfoster I can still replicate in Firefox and Edge (_seems_ slightly tougher to replicate in Edge).

**Pull request merged**
