### PR TITLE
issue/2967 Reworked scrollingContainer

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes https://github.com/adaptlearning/adapt_framework/issues/2967

### Fixed
* Replaced jquery based fix with browser based fix to enhance the embeddedness of the solution
  * Replaced `window.scrollY`, `window.scrollX`, `window.pageYOffset`, `window.pageXOffset`, `html.scrollHeight`, `html.scrollWidth` and `window.scrollTo` so that they have impact on the `#app` container and use its values rather than those from the `html` tag
* Added `MouseEvent` fix to ensure `event.pageX` and `event.pageY` are relative to the scroll of the `#app` container rather than the `html` tag
  * Replaced `MouseEvent.prototype.pageX` and `MouseEvent.prototype.pageY` so that they take the approprate values from the `#app` container scroll position rather than the `html` tag scroll position

### Changed
* Linting issues

### Testing
1. Clone the framework and set core to the correct branch:
```sh
git clone https://github.com/adaptlearning/adapt_framework 2967
cd 2967
npm install && adapt devinstall
cd src/core
git checkout issue/2967
cd ../../
```

2. Enable the scrolling container by changing `src/course/config.json` `_scrollingContainer._isEnabled` to `true`.
3. Add volume controls to the media component by adding to `src/course/en/components.json` component `c-40`, `"_showVolumeControl": true,`

3. Build the project:
```sh
grunt dev
```

### CODE REVIEW

**Review by kirsty-hames — APPROVED** [review]
Fixes #2967 confirmed - testing Safari, Chrome and Firefox on MacOS

**Review by danielghost — APPROVED** [review]

**Review by eleanor-heath — APPROVED** [review]

**Comment by oliverfoster** [comment]
I have a different candidate to improve this further. Please don't yet merge this.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
closing in favour of https://github.com/adaptlearning/adapt-contrib-core/pull/16

**Pull request closed without merging**
