### PR TITLE
Fix: aria-level is set to "0" for headings (fixes #233)

### LINKED ISSUE #233: aria-level is set to "0" for headings
Since #146 has ariaLevel use ?? to check the level override, it considers the 0 default value to be a valid level, and ends up setting aria-level="0" on all headings.

### PR DESCRIPTION
**Pull request by hanshillen**
Fixes #233

### Fix

* Change nullish coalescing operator to logical OR for ariaLevel check, so that 0 is not accepted as a level value.

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
I would rather warn that the heading level is invalid. Where is _ariaLevel beening set to 0? Is it human error or some default?

**Comment by hanshillen** [comment]
It defaults to 0 in page.model.schema, article.model.schema, block.model.schema, and component.model.schema:

```json
    "_ariaLevel": {
      "type": "number",
      "default": 0,
      "isSetting": true,
      "inputType": "Number",
      "validators": ["number"],
      "help": "If you need to override the default component ARIA level (as defined in Configuration Settings), set this to any number greater than 0."
    },
```

So the AAT will set _ariaLevel to 0 for every model that it creates.

**Comment by oliverfoster** [comment]
Hmm, can you just put an if block at the top of the function to correct this?
```js
if (override === 0) override = null;
```

**Comment by hanshillen** [comment]
> Hmm, can you just put an if block at the top of the function to correct this?

Done

> The `_ariaLevel` type should be changed to a string really.

Agreed, and then check for an empty string instead

**Review by oliverfoster — APPROVED** [review]

**Review by StuartNicholls — APPROVED** [review]

**Pull request merged**
