### PR TITLE
Update: jquery.resize.js to use ResizeObserver

### LINKED ISSUE #576: jquery.resize update to use ResizeObserver instead of manual calculations
### Subject of the issue
[ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) is now long fully supported https://caniuse.com/resizeobserver

It works in a similar way to MutationObserver, in that it allows well timed callbacks against the browser's rendering lifecycle, giving us the ability to immediately capture resize events as they happen and respond to them in a way that doesn't cause rendering glitches. It is much more performant and much less resource intensive than our current approach of measuring and comparing on expiring intervals and at strategic events.

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #576 

### Update
* Use browser API [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) to reduce code complexity and increase performance

Refs:
* https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver
* https://caniuse.com/resizeobserver

Note:
* Not ie11 compatible

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Comment by oliverfoster** [comment]
Ready now, apologies

**Review by joe-allen-89 — APPROVED** [review]
Tested across multiple browsers, all working as expected 👍

**Pull request merged**
